# This file was generated by GoReleaser. DO NOT EDIT.
cask "qodercli" do
  # Create installation source marker after installation for update detection
  postflight do
    # Place marker file in the storage directory
    marker = staged_path/'.qodercli-install-resource'
    File.write(marker, "homebrew-cask")
    marker.chmod(0644)

    # Ensure binary has executable permissions
    (staged_path/"qodercli").chmod(0755)

    bin_binary = HOMEBREW_PREFIX/"bin"/"qodercli"
    system bin_binary, "--version"
  end

  name "qodercli"
  desc "Qoder AI CLI tool - Terminal-based AI assistant for code development"
  homepage "https://qoder.com"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qodercli"

  on_macos do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_amd64.zip"
      sha256 "f8ca8a28a204dd57c345568c5378d19633c1c9ae1a3df981e06dd91551b0d683"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_arm64.zip"
      sha256 "22449dde853ec8d5c2d5a926b9176b9594af99d8b49c28fb3bfbbbadeba74f7f"
    end
  end

  on_linux do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_amd64.tar.gz"
      sha256 "9a476f87a856e7a9530c2b91484f929c412905bacb34d61631fab535898af1d7"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_arm64.tar.gz"
      sha256 "79067bd5fdee0234b46c096c95a884dad53961f58d32e913d11c42b314ec1fe4"
    end
  end

  # No zap stanza required
end
