# This file was generated by GoReleaser. DO NOT EDIT.
cask "qodercli" do
  # Create installation source marker after installation for update detection
  postflight do
    # Place marker file in the storage directory
    marker = staged_path/'.qodercli-install-resource'
    File.write(marker, "homebrew-cask")
    marker.chmod(0644)

    # Ensure binary has executable permissions
    (staged_path/"qodercli").chmod(0755)

    bin_binary = HOMEBREW_PREFIX/"bin"/"qodercli"
    system bin_binary, "--version"
  end

  name "qodercli"
  desc "Qoder AI CLI tool - Terminal-based AI assistant for code development"
  homepage "https://qoder.com"
  version "0.0.13-preview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qodercli"

  on_macos do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_amd64.zip"
      sha256 "d47b852304e980926f2b617ee107928206d787e305d18433a0dd73fee23dc5db"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_arm64.zip"
      sha256 "fe2037cd693300b32996b60790b23e51374f5782738b5d87f543da106a6ac3d3"
    end
  end

  on_linux do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_amd64.tar.gz"
      sha256 "bc2ced59f9ca2f70fcf09ac3cee744c205a956f4c1f59c4ba5223c1ac1f0a167"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_arm64.tar.gz"
      sha256 "b509abb85fb4e97de2f04d6b2dfead1f5a49f952e65f38932ee6ee38c9f0954a"
    end
  end

  # No zap stanza required
end
