# This file was generated by GoReleaser. DO NOT EDIT.
cask "qodercli" do
  # Create installation source marker after installation for update detection
  postflight do
    # Place marker file in the storage directory
    marker = staged_path/'.qodercli-install-resource'
    File.write(marker, "homebrew-cask")
    marker.chmod(0644)

    # Ensure binary has executable permissions
    (staged_path/"qodercli").chmod(0755)

    bin_binary = HOMEBREW_PREFIX/"bin"/"qodercli"
    system bin_binary, "--version"
  end

  name "qodercli"
  desc "Qoder AI CLI tool - Terminal-based AI assistant for code development"
  homepage "https://qoder.com"
  version "0.0.9-preview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qodercli"

  on_macos do
    on_intel do
      url "qoder-ide.oss-ap-southeast-1.aliyuncs.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_amd64.zip"
      sha256 "b15c7e3692a322c7f605a097aa24827f7465d4f4037e0548eae4e99abd0a1ba9"
    end
    on_arm do
      url "qoder-ide.oss-ap-southeast-1.aliyuncs.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_arm64.zip"
      sha256 "bec7c81aabf5c42fcf94b78402508c0e742b6eb36bc7b739f49e54138f05c445"
    end
  end

  on_linux do
    on_intel do
      url "qoder-ide.oss-ap-southeast-1.aliyuncs.com/qodercli/releases/#{version}/qodercli_#{version}_linux_amd64.tar.gz"
      sha256 "7e9e33d234c9d819290872c11daef8cbcf5df92e9525533e8ad3932a0420c9d0"
    end
    on_arm do
      url "qoder-ide.oss-ap-southeast-1.aliyuncs.com/qodercli/releases/#{version}/qodercli_#{version}_linux_arm64.tar.gz"
      sha256 "0371b085c472269f5e565f718957e79b8fad2135c8ab16b0592276ce6863f233"
    end
  end

  # No zap stanza required
end
